// <auto-generated />
using System;
using GrupoBlancoChallenge.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrupoBlancoChallenge.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708200859_CompanySaleOutcome")]
    partial class CompanySaleOutcome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.DecisionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BrandImageImpact")
                        .HasColumnType("integer");

                    b.Property<int>("ClientsImpact")
                        .HasColumnType("integer");

                    b.Property<string>("Consequence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OperationalEfficiencyImpact")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationalClimateImpact")
                        .HasColumnType("integer");

                    b.Property<int>("RentabilityImpact")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("decision_options", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.GameDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionOptionId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("game_decisions", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BrandImage")
                        .HasColumnType("integer");

                    b.Property<int>("Clients")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentScenarioOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FinalRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinishedAtMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("OperationalEfficiency")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationalClimate")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rentability")
                        .HasColumnType("integer");

                    b.Property<bool>("WasCompanySold")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.GameSessionScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("GameSessionId", "Month")
                        .IsUnique();

                    b.HasIndex("GameSessionId", "Position")
                        .IsUnique();

                    b.ToTable("game_session_scenarios", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.RankingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FinalRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinishedAtMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WasCompanySold")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ranking_entries", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("scenarios", (string)null);
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.DecisionOption", b =>
                {
                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.Scenario", "Scenario")
                        .WithMany("Options")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.GameDecision", b =>
                {
                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.DecisionOption", "DecisionOption")
                        .WithMany()
                        .HasForeignKey("DecisionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecisionOption");

                    b.Navigation("GameSession");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.GameSessionScenario", b =>
                {
                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrupoBlancoChallenge.Domain.Entities.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("GrupoBlancoChallenge.Domain.Entities.Scenario", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
